function PlotPulseTimeHist(TimeHistFile)
% PLOTPULSETIMEHIST Plot GE pulse sequence time history file (.tgt.his) generated by WTools
%    PLOTPULSETIMEHIST(TimeHistFile) specifies the file name.
%
%    Example:
%    PLOTPULSETIMEHIST('epi.tgt.his')
%
%    Subfunctions:
%    See also: plotPdFile

% AUTHOR    : Yi Sui
% DATE      : 01/16/2017

[~,basename,~] = fileparts(TimeHistFile); %remove .his
[~,basename,~] = fileparts(basename); %remove .tgt
basename = matlab.lang.makeValidName(['plot_', basename]);%remove invalid characters
mfile = [basename, '.m'];
result = perl('readTimeHist.pl',TimeHistFile,mfile);%call perl script to parse .his file and create a matlab script

% ax = findobj(gcf,'type','axes');
% for k=1:numel(ax)
%     addPulseList(ax(k))
% end
run(mfile);% run the matlab script